apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulsebox.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulsebox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulsebox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pulsebox.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "pulsebox.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pulsebox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-addr=:{{ .Values.ports.metrics }}
            - --http-addr=:{{ .Values.ports.http }}
            - --pvc-pending-grace={{ .Values.pvcPendingGrace }}
            {{- if not .Values.rbac.clusterWide }}
            - --namespace={{ include "pulsebox.watchNamespace" . }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
            - name: http
              containerPort: {{ .Values.ports.http }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
