apiVersion: v2
name: pulsebox
description: Kubernetes-native cluster health exporter with a live topology dashboard
type: application
version: 1.3.0
appVersion: "1.3.0"
keywords:
  - kubernetes
  - monitoring
  - prometheus
  - health
  - topology
home: https://github.com/Ramtinboreili/Pulsebox
sources:
  - https://github.com/Ramtinboreili/Pulsebox
maintainers:
  - name: Ramtin Boreili
